configuration :
    log :
        enabled : true
        handler : RotatingFile

graphs :
    - template : Test_Random
      enabled : true
      arguments :
          # Minimum number
          min : 5
          # Maximum number
          max : 10

    - template : Unix_LoadAverages
      enabled : false

    - template : Unix_LoggedUsers
      enabled : false

    - template : Unix_TcpConnections
      enabled : false

    - template : Unix_Processes
      enabled : false

    - template : Unix_DiskStats
      enabled : false
      arguments :
          # Filesystem name
          disk : /dev/*

    - template : Weather_Google
      enabled : false
      arguments :
          # Location, ex : Istanbul, Turkey
          location : Place
          # Type of unit (c/f)
          type : c