configuration :
    log :
        enabled : true
        handler : RotatingFile

graphs :
    - template : Test_Random
      enabled : true
      arguments :
          min : 5
          max : 10

    - template : Unix_LoadAverages
      enabled : true

    - template : Unix_LoggedUsers
      enabled : true

    - template : Unix_TcpConnections
      enabled : true

    - template : Unix_Processes
      enabled : true

    - template : Weather_Google
      enabled : true
      arguments :
          location : Istanbul,Turkey
          type : c