graphs :
    - template : TestRandom
      enabled : true
      arguments :
          # Minimum number
          min : 5
          # Maximum number
          max : 10

    - template : UnixLoadAverages
      enabled : false

    - template : UnixLoggedUsers
      enabled : false

    - template : UnixTcpConnections
      enabled : false

    - template : UnixProcesses
      enabled : false

    - template : UnixDiskStats
      enabled : false
      arguments :
          # Filesystem name
          disk : /dev/*

    - template : GoogleWeather
      enabled : false
      arguments :
          # Location, ex : Istanbul, Turkey
          location : Place
          # Type of unit (c/f)
          type : c
