defaults :
    foo : bar
    bar : baz
templates :
    - name : template-name
      enabled : true
      arguments :
          foo : bar
          bar : baz
    - name : other-template-name
      enabled : false
      arguments :
          foo : bar